### ISSUE TITLE
Links broken after docker rm

### ISSUE THREAD

**Issue by arnaubennassar** [LycheeOrg/Lychee-Laravel-Docker#34]
After running `sudo docker-compose down` or `sudo docker rm lychee` all the pictures links are broken: the http requests return 404. "Open original" option also returns 404, however the download option works fine for all the different sizes including original and entire albums.

It only happens after `sudo docker-compose down` or `sudo docker rm lychee`. Rebooting the server or `sudo docker {restart, stop + star} lychee` behave well.

My docker-compose.yml:
```
version: "2"
services:
  lychee:
    container_name: lychee
    restart: always
    image: lycheeorg/lychee-laravel
    expose:
        - 80
    volumes:
        - /home/bros/fast-data/lychee/conf:/conf
        - /home/bros/big-data/lychee/uploads:/uploads
    environment:
        - PHP_TZ=***
        - DB_CONNECTION=mysql
        - DB_HOST=***
        - DB_PORT=***
        - DB_DATABASE=***
        - DB_USERNAME=***
        - DB_PASSWORD=***
        - VIRTUAL_HOST=***
        - VIRTUAL_PORT=80
        - LETSENCRYPT_HOST=***
        - LETSENCRYPT_EMAIL=***
networks:
    default:
        external:
            name: nginx-net
 ```

Note:
* I'm using an already running MariaDB container, and the connection to it seems just fine.
* I'm using a nginx + letsencrypt setup based on [this](https://github.com/jwilder/nginx-proxy)

Diagnostic:
```
    Diagnostics
    -----------
    Info: Latest version of PHP is 7.4
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    ------------------
    Lychee-front Version:      3.2.16
    Lychee Version (git):      bae5f2b (master) - Data not in Cache
    DB Version:                040000
    System:                    Linux
    PHP Version:               7.3
    MySQL Version:             10.4.12-MariaDB-1:10.4.12+maria~bionic-log
    
    Lychee total space:        65.14 MB
    Upload folder space:       8.00 B
    System total space:        31.61 GB
    System free space:         16.26 GB (51%)
    
    Imagick:                   1
    Imagick Active:            1
    Imagick Version:           1690
    GD Version:                2.2.5

    Config Information
    ------------------
    version:                   040000
    check_for_updates:         0
    sorting_Photos_col:        takestamp
    sorting_Photos_order:      ASC
    sorting_Albums_col:        max_takestamp
    sorting_Albums_order:      ASC
    imagick:                   1
    skip_duplicates:           0
    small_max_width:           0
    small_max_height:          360
    medium_max_width:          1920
    medium_max_height:         1080
    lang:                      en
    layout:                    1
    image_overlay:             1
    image_overlay_type:        desc
    default_license:           none
    compression_quality:       90
    full_photo:                1
    delete_imported:           0
    Mod_Frame:                 1
    Mod_Frame_refresh:         30
    thumb_2x:                  1
    small_2x:                  1
    medium_2x:                 1
    landing_page_enable:       0
    landing_owner:             Arnau Bennassar
    landing_title:             Arnau Bennassar
    landing_subtitle:          Cats, Dogs & Humans Photography
    landing_facebook:          https://www.facebook.com/JohnSmith
    landing_flickr:            https://www.flickr.com/JohnSmith
    landing_twitter:           https://www.twitter.com/JohnSmith
    landing_instagram:         https://instagram.com/JohnSmith
    landing_youtube:           https://www.youtube.com/JohnSmith
    landing_background:        dist/cat.jpg
    site_title:                Lychee v4
    site_copyright_enable:     0
    site_copyright_begin:      2019
    site_copyright_end:        2019
    additional_footer_text:    
    display_social_in_gallery: 0
    public_search:             0
    public_recent:             0
    recent_age:                1
    public_starred:            0
    downloadable:              1
    photos_wraparound:         1
    map_display:               1
    zip64:                     1
    map_display_public:        0
    map_provider:              Wikimedia
    force_32bit_ids:           0
    map_include_subalbums:     0
    update_check_every_days:   3
    has_exiftool:              1
    share_button_visible:      1
    import_via_symlink:        0
    has_ffmpeg:                1
```
